/**
 * Bundle installer — auto-installs Marblo's required harness assets
 * (tf-* slash commands and skills) into the user's `~/.claude/` on
 * app start. Idempotent: writes a content-hash marker and skips re-copy
 * when the marker matches the current bundle's content hash.
 *
 * The marker is a hash of the bundled source files (paths + contents),
 * NOT the app version. This means shipping edited tf-* commands/skills
 * propagates to every user on their next launch even without an app
 * version bump — the hash changes whenever the shipped content changes.
 *
 * The Marblo MCP server is NOT registered into any global CLI config
 * here. Marblo-spawned agents reach it via per-agent isolated configs
 * generated by AgentConfigGenerator; the user's external terminal CLI
 * sessions are managed independently (typically with their own
 * taskforce MCP for cross-app TaskForce access).
 */
import crypto from "crypto";
import fs from "fs";
import os from "os";
import path from "path";
import { app } from "electron";

const BUNDLE_NAME = "marblo-bundled-harness";
const VERSION_MARKER = ".marblo-bundle-version";

interface InstallResult {
  installed: number;
  skipped: number;
  errors: string[];
}

type JsonObject = Record<string, unknown>;

/** Locate the source directory for bundled assets. */
function findBundleSource(): { commands: string; skills: string } | null {
  const candidates: Array<{ commands: string; skills: string }> = [];

  // Production: electron-builder copies bundled-harness/ into resources.
  candidates.push({
    commands: path.join(process.resourcesPath, "bundled-harness", "commands"),
    skills: path.join(process.resourcesPath, "bundled-harness", "skills"),
  });

  // Dev: bundled assets live one directory up from v3 (repo root .claude/).
  // app.getAppPath() points to v3 in dev; .. is the repo root.
  const repoRoot = path.resolve(app.getAppPath(), "..");
  candidates.push({
    commands: path.join(repoRoot, ".claude", "commands"),
    skills: path.join(repoRoot, ".claude", "skills"),
  });

  for (const c of candidates) {
    if (fs.existsSync(c.commands) && fs.existsSync(c.skills)) {
      return c;
    }
  }
  return null;
}

/**
 * Compute a deterministic content hash of the bundle source. Walks both
 * the commands and skills directories recursively, collects (relativePath,
 * content) pairs, sorts them by path for a stable ordering, and folds each
 * into a single sha256 digest (path + NUL + content). The resulting hex
 * digest changes whenever any shipped file's path or content changes, so
 * it can serve as a version-independent install marker.
 */
export function computeBundleHash(source: {
  commands: string;
  skills: string;
}): string {
  const entries: Array<{ rel: string; content: Buffer }> = [];

  const walk = (root: string, dir: string, prefix: string): void => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(root, abs, prefix);
      } else if (entry.isFile()) {
        // Normalise path separators so the hash is stable across platforms.
        const rel =
          prefix + "/" + path.relative(root, abs).split(path.sep).join("/");
        entries.push({ rel, content: fs.readFileSync(abs) });
      }
    }
  };

  if (fs.existsSync(source.commands)) {
    walk(source.commands, source.commands, "commands");
  }
  if (fs.existsSync(source.skills)) {
    walk(source.skills, source.skills, "skills");
  }

  entries.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));

  const hash = crypto.createHash("sha256");
  for (const e of entries) {
    hash.update(e.rel);
    hash.update("\0");
    hash.update(e.content);
  }
  return hash.digest("hex");
}

/**
 * Copy src→dst only when the destination is missing or its content
 * differs. Avoids needlessly rewriting (and bumping mtime on) files the
 * user already has identical copies of, minimising churn. Returns true
 * when a write actually occurred.
 */
function copyFileIfChanged(src: string, dst: string): boolean {
  try {
    if (fs.existsSync(dst)) {
      const a = fs.readFileSync(src);
      const b = fs.readFileSync(dst);
      if (a.equals(b)) return false;
    }
  } catch {
    // Comparison failed — fall through and copy to be safe.
  }
  fs.copyFileSync(src, dst);
  return true;
}

function copyDirRecursive(
  src: string,
  dst: string
): { seen: number; copied: number } {
  fs.mkdirSync(dst, { recursive: true });
  let seen = 0;
  let copied = 0;
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const dstPath = path.join(dst, entry.name);
    if (entry.isDirectory()) {
      const r = copyDirRecursive(srcPath, dstPath);
      seen += r.seen;
      copied += r.copied;
    } else if (entry.isFile()) {
      seen += 1;
      if (copyFileIfChanged(srcPath, dstPath)) copied += 1;
    }
  }
  return { seen, copied };
}

function isJsonObject(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Claude Code removed the old permissions.defaultMode="auto" spelling.
 * Marblo historically left user settings untouched, so users who installed
 * old bundles can end up with `claude doctor` failures even though the current
 * bundle no longer writes that value. Migrate only the known stale value.
 */
export function normalizeClaudeSettings(settingsPath: string): boolean {
  if (!fs.existsSync(settingsPath)) return false;
  let parsed: unknown;
  try {
    parsed = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
  } catch {
    return false;
  }
  if (!isJsonObject(parsed)) return false;
  const permissions = parsed.permissions;
  if (!isJsonObject(permissions)) return false;
  if (permissions.defaultMode !== "auto") return false;

  permissions.defaultMode = "bypassPermissions";
  try {
    fs.writeFileSync(
      settingsPath,
      JSON.stringify(parsed, null, 2) + "\n",
      "utf-8"
    );
    console.log(
      "[BundleInstaller] Migrated Claude permissions.defaultMode auto → bypassPermissions"
    );
    return true;
  } catch (err) {
    console.warn("[BundleInstaller] Failed to migrate Claude settings:", err);
    return false;
  }
}

/**
 * Run the bundled installer. Skips work when the user already has the
 * current bundle content installed (marker file matches the content hash).
 */
export async function installBundledHarness(): Promise<InstallResult> {
  const result: InstallResult = { installed: 0, skipped: 0, errors: [] };
  const userClaudeDir = path.join(os.homedir(), ".claude");
  const userCommandsDir = path.join(userClaudeDir, "commands");
  const userSkillsDir = path.join(userClaudeDir, "skills");
  const markerPath = path.join(userClaudeDir, VERSION_MARKER);
  const userSettingsPath = path.join(userClaudeDir, "settings.json");

  normalizeClaudeSettings(userSettingsPath);

  // Resolve the bundle source first — the marker is derived from its
  // content hash, so we need the source before we can decide to skip.
  const source = findBundleSource();
  if (!source) {
    const msg =
      "Bundle source not found. Skipping (likely running outside of packaged app or repo root).";
    console.warn(`[BundleInstaller] ${msg}`);
    result.errors.push(msg);
    return result;
  }

  const hash = computeBundleHash(source);
  const targetMarker = `${BUNDLE_NAME}@${hash}`;

  // Skip if user already has this exact content installed.
  try {
    if (fs.existsSync(markerPath)) {
      const existing = fs.readFileSync(markerPath, "utf-8").trim();
      if (existing === targetMarker) {
        result.skipped += 1;
        console.log(
          `[BundleInstaller] Skipping — content hash marker matches (${targetMarker})`
        );
        return result;
      }
    }
  } catch (err) {
    // Marker unreadable — proceed with install.
    console.warn("[BundleInstaller] Could not read content hash marker:", err);
  }

  fs.mkdirSync(userCommandsDir, { recursive: true });
  fs.mkdirSync(userSkillsDir, { recursive: true });

  // Number of bundled tf-* files seen (regardless of whether they needed
  // rewriting). Used to gate the marker write — we only mark when there
  // was real bundle content to install.
  let totalSeen = 0;

  // Copy tf-* commands.
  try {
    for (const file of fs.readdirSync(source.commands)) {
      if (!file.startsWith("tf-") || !file.endsWith(".md")) continue;
      const src = path.join(source.commands, file);
      const dst = path.join(userCommandsDir, file);
      totalSeen += 1;
      if (copyFileIfChanged(src, dst)) result.installed += 1;
    }
  } catch (err) {
    const msg = `Failed to copy commands: ${
      err instanceof Error ? err.message : err
    }`;
    console.warn(`[BundleInstaller] ${msg}`);
    result.errors.push(msg);
  }

  // Copy tf-* skills directories.
  try {
    for (const entry of fs.readdirSync(source.skills, {
      withFileTypes: true,
    })) {
      if (!entry.isDirectory()) continue;
      if (!entry.name.startsWith("tf-")) continue;
      const src = path.join(source.skills, entry.name);
      const dst = path.join(userSkillsDir, entry.name);
      const r = copyDirRecursive(src, dst);
      totalSeen += r.seen;
      result.installed += r.copied;
    }
  } catch (err) {
    const msg = `Failed to copy skills: ${
      err instanceof Error ? err.message : err
    }`;
    console.warn(`[BundleInstaller] ${msg}`);
    result.errors.push(msg);
  }

  // NOTE: We intentionally do NOT register the Marblo MCP into any
  // global CLI config (~/.claude.json, ~/.codex/config.toml,
  // ~/.gemini/settings.json). Marblo-spawned agents reach the MCP via
  // their per-agent isolated config (AgentConfigGenerator), and the
  // user's *external* terminal CLI sessions manage their own MCP setup
  // (typically taskforce MCP for cross-app TaskForce access) — clobbering
  // those configs would conflict with that workflow.

  // Write the content hash marker once the install completed cleanly and
  // there was actual bundle content. We gate on totalSeen (not installed)
  // so that a re-copy whose files are already byte-identical still
  // refreshes the marker and avoids re-checking on every future launch.
  if (totalSeen > 0 && result.errors.length === 0) {
    try {
      fs.writeFileSync(markerPath, targetMarker, "utf-8");
    } catch (err) {
      console.warn(
        "[BundleInstaller] Could not write content hash marker:",
        err
      );
    }
  }

  console.log(
    `[BundleInstaller] Installed ${result.installed} changed files (${totalSeen} bundled), skipped ${result.skipped}, errors ${result.errors.length}`
  );
  return result;
}
