// ⚠ 생성물 — 손으로 고치지 않는다.
// `npm run bench:swe:emit` (= scripts/bench/report.ts --emit-ours) 가 덮어쓴다.
// 정본은 실행 머신의 `results/runs.jsonl` 이고, 이 파일은 그 파생이다.
// 스키마·검증·주석은 형제 파일 `model-bench-ours.ts` 에 있다.

import type { OurBenchReport } from "./model-bench-ours";

export const OUR_BENCH_DATA: OurBenchReport = {
  meta: {
    label: "our-measured",
    dataset: "princeton-nlp/SWE-bench_Verified",
    instances: [
      "django__django-14725",
      "django__django-14771",
      "django__django-15022",
      "django__django-15037",
      "django__django-15098",
      "django__django-15103",
      "django__django-15128",
      "django__django-15161",
      "django__django-15252",
      "django__django-15268",
      "django__django-15278",
      "django__django-15280",
      "django__django-15375",
      "django__django-15503",
      "django__django-15629",
      "django__django-15731",
      "django__django-15814",
      "django__django-15851",
      "django__django-15863",
      "django__django-15957",
      "django__django-15987",
      "django__django-16136",
      "django__django-16256",
      "django__django-16263",
      "django__django-16315",
      "django__django-16429",
      "django__django-16560",
      "django__django-16631",
      "django__django-16642",
    ],
    totalRuns: 325,
    scaffold:
      "marblo-swebench-spike/v1(single-shot,no-mcp,no-board) · marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board) · marblo-swebench-spike/v3b(20-discrimination-tuned,single-shot,no-mcp,no-board,metered) · marblo-swebench-spike/v3a(12-mixed-difficulty,single-shot,no-mcp,no-board,metered)",
    execEnv: "native-venv/macos-arm64(no-docker)",
    graderVersion: "v2(id-alias+mismatch-gate)",
    generatedAt: "2026-09-05T08:50:40.551Z",
    reportPath: "v3/docs/benchmark/generated-report.md",
    disclaimers: [
      "★이 표의 숫자는 **우리가 우리 스폰 경로로 직접 잰 값**이다. 벤더 공개치(`electron/model-bench-reference.ts`)와 **같은 표에 놓지 않는다**.",
      "★**(모델, 하네스)** 비교이며 단발 런이라 재실행 분산은 아직 측정하지 않았다.",
      "★실행환경이 공식 SWE-bench Docker 이미지가 아니므로 **공식 리더보드 수치와 비교할 수 없다.** 여기서 읽어도 되는 것은 *같은 execEnv·같은 scaffold 안에서의 상대 비교*뿐이다.",
    ],
  },
  cells: [
    {
      harness: "noop",
      model: null,
      effort: null,
      graded: 3,
      resolved: 0,
      resolvedPct: 0,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "gold",
      model: null,
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-opus-5",
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 33,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "2.1.226 (Claude Code)",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-fable-5",
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 42,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "2.1.226 (Claude Code)",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-sonnet-5",
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 21,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "2.1.226 (Claude Code)",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-sol",
      effort: "medium",
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 39,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.144.5",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-luna",
      effort: "medium",
      graded: 3,
      resolved: 2,
      resolvedPct: 66.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 55,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.144.5",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "noop",
      model: null,
      effort: null,
      graded: 12,
      resolved: 0,
      resolvedPct: 0,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "gold",
      model: null,
      effort: null,
      graded: 24,
      resolved: 24,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-opus-5",
      effort: null,
      graded: 12,
      resolved: 11,
      resolvedPct: 91.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 180,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "2.1.227 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-fable-5",
      effort: null,
      graded: 12,
      resolved: 12,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 94,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "2.1.227 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-sonnet-5",
      effort: null,
      graded: 12,
      resolved: 9,
      resolvedPct: 75,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 147,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "2.1.227 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-sol",
      effort: "medium",
      graded: 12,
      resolved: 11,
      resolvedPct: 91.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 92,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.147.0",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-terra",
      effort: "medium",
      graded: 12,
      resolved: 9,
      resolvedPct: 75,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 61,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.147.0",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-luna",
      effort: "medium",
      graded: 12,
      resolved: 10,
      resolvedPct: 83.33333333333334,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 94,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.147.0",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.5",
      effort: "medium",
      graded: 12,
      resolved: 11,
      resolvedPct: 91.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 124,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.147.0",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "grok",
      model: "grok-4.5",
      effort: null,
      graded: 12,
      resolved: 10,
      resolvedPct: 83.33333333333334,
      noOutput: 2,
      errored: 0,
      avgAgentSeconds: 90,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "grok 1.0.0 (3cd0d0cbcebe)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "solar-pro4",
      effort: "medium",
      graded: 12,
      resolved: 3,
      resolvedPct: 25,
      noOutput: 8,
      errored: 0,
      avgAgentSeconds: 226,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.148.0",
      vendorRoute:
        "upstage/openai-compat via local responses→chat bridge (codex custom provider, apikey auth)",
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "deepseek-v4-flash",
      effort: "high",
      graded: 12,
      resolved: 11,
      resolvedPct: 91.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 73,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.149.0",
      vendorRoute:
        "deepseek/responses-native direct (codex custom provider, apikey auth, model_catalog_json → apply_patch=freeform)",
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "deepseek-v4-pro",
      effort: "high",
      graded: 12,
      resolved: 12,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 142,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.149.0",
      vendorRoute:
        "deepseek/responses-native direct (codex custom provider, apikey auth, model_catalog_json → apply_patch=freeform)",
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "gold",
      model: null,
      effort: null,
      graded: 20,
      resolved: 20,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v3b(20-discrimination-tuned,single-shot,no-mcp,no-board,metered)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "noop",
      model: null,
      effort: null,
      graded: 20,
      resolved: 0,
      resolvedPct: 0,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      inputTokens: null,
      outputTokens: null,
      listCostUsd: null,
      vendorCostUsd: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v3b(20-discrimination-tuned,single-shot,no-mcp,no-board,metered)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-fable-5-1",
      effort: null,
      graded: 12,
      resolved: 11,
      resolvedPct: 91.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 98,
      inputTokens: 4794624,
      outputTokens: 81316,
      listCostUsd: 52.01204,
      vendorCostUsd: 12.74539225,
      cliVersion: "2.1.261 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v3a(12-mixed-difficulty,single-shot,no-mcp,no-board,metered)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-6-astra",
      effort: "medium",
      graded: 12,
      resolved: 10,
      resolvedPct: 83.33333333333334,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 61,
      inputTokens: 1703939,
      outputTokens: 16551,
      listCostUsd: 17.86694,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.153.3",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v3a(12-mixed-difficulty,single-shot,no-mcp,no-board,metered)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-opus-5",
      effort: null,
      graded: 12,
      resolved: 10,
      resolvedPct: 83.33333333333334,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 74,
      inputTokens: 6469726,
      outputTokens: 64673,
      listCostUsd: 33.965455,
      vendorCostUsd: 8.438325500000001,
      cliVersion: "2.1.261 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v3a(12-mixed-difficulty,single-shot,no-mcp,no-board,metered)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-fable-5-1",
      effort: null,
      graded: 20,
      resolved: 18,
      resolvedPct: 90,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 243,
      inputTokens: 11053578,
      outputTokens: 173610,
      listCostUsd: 119.21628,
      vendorCostUsd: 25.13280725,
      cliVersion: "2.1.261 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v3b(20-discrimination-tuned,single-shot,no-mcp,no-board,metered)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-6-astra",
      effort: "medium",
      graded: 20,
      resolved: 14,
      resolvedPct: 70,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 69,
      inputTokens: 3843724,
      outputTokens: 27964,
      listCostUsd: 39.83544,
      vendorCostUsd: null,
      cliVersion: "codex-cli 0.153.4",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v3b(20-discrimination-tuned,single-shot,no-mcp,no-board,metered)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-opus-5",
      effort: null,
      graded: 20,
      resolved: 19,
      resolvedPct: 95,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 171,
      inputTokens: 17886666,
      outputTokens: 179103,
      listCostUsd: 93.910905,
      vendorCostUsd: 20.679518,
      cliVersion: "2.1.261 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v3b(20-discrimination-tuned,single-shot,no-mcp,no-board,metered)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
  ],
  instances: [
    {
      instanceId: "django__django-14725",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 64,
          p2pTotal: 64,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 64,
          p2pTotal: 64,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 64,
          p2pTotal: 64,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 64,
          p2pTotal: 64,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 64,
          p2pTotal: 64,
        },
      ],
    },
    {
      instanceId: "django__django-14771",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 60,
          p2pTotal: 60,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 60,
          p2pTotal: 60,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 60,
          p2pTotal: 60,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 60,
          p2pTotal: 60,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 60,
          p2pTotal: 60,
        },
      ],
    },
    {
      instanceId: "django__django-15022",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 56,
          p2pTotal: 56,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 56,
          p2pTotal: 56,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 56,
          p2pTotal: 56,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 56,
          p2pTotal: 56,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 56,
          p2pTotal: 56,
        },
      ],
    },
    {
      instanceId: "django__django-15037",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 14,
          p2pTotal: 14,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 14,
          p2pTotal: 14,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 14,
          p2pTotal: 14,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 14,
          p2pTotal: 14,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 14,
          p2pTotal: 14,
        },
      ],
    },
    {
      instanceId: "django__django-15098",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 88,
          p2pTotal: 88,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 2,
          p2pPassed: 88,
          p2pTotal: 88,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 88,
          p2pTotal: 88,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 2,
          p2pPassed: 87,
          p2pTotal: 88,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 88,
          p2pTotal: 88,
        },
      ],
    },
    {
      instanceId: "django__django-15103",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 17,
          p2pTotal: 17,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 2,
          p2pPassed: 17,
          p2pTotal: 17,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 17,
          p2pTotal: 17,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 17,
          p2pTotal: 17,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 17,
          p2pTotal: 17,
        },
      ],
    },
    {
      instanceId: "django__django-15128",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 282,
          p2pTotal: 282,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 282,
          p2pTotal: 282,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 282,
          p2pTotal: 282,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 282,
          p2pTotal: 282,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 282,
          p2pTotal: 282,
        },
      ],
    },
    {
      instanceId: "django__django-15161",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 208,
          p2pTotal: 208,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 208,
          p2pTotal: 208,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 208,
          p2pTotal: 208,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 208,
          p2pTotal: 208,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 208,
          p2pTotal: 208,
        },
      ],
    },
    {
      instanceId: "django__django-15252",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 34,
          p2pTotal: 34,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 2,
          p2pPassed: 34,
          p2pTotal: 34,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 2,
          p2pPassed: 34,
          p2pTotal: 34,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 2,
          p2pPassed: 34,
          p2pTotal: 34,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 34,
          p2pTotal: 34,
        },
      ],
    },
    {
      instanceId: "django__django-15268",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 130,
          p2pTotal: 130,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 130,
          p2pTotal: 130,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 130,
          p2pTotal: 130,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 130,
          p2pTotal: 130,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 130,
          p2pTotal: 130,
        },
      ],
    },
    {
      instanceId: "django__django-15278",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 138,
          p2pTotal: 138,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 138,
          p2pTotal: 138,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 138,
          p2pTotal: 138,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 138,
          p2pTotal: 138,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 138,
          p2pTotal: 138,
        },
      ],
    },
    {
      instanceId: "django__django-15280",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 85,
          p2pTotal: 85,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 85,
          p2pTotal: 85,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 85,
          p2pTotal: 85,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 85,
          p2pTotal: 85,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 85,
          p2pTotal: 85,
        },
      ],
    },
    {
      instanceId: "django__django-15375",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 95,
          p2pTotal: 95,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 95,
          p2pTotal: 95,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 95,
          p2pTotal: 95,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 95,
          p2pTotal: 95,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 95,
          p2pTotal: 95,
        },
      ],
    },
    {
      instanceId: "django__django-15503",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 78,
          p2pTotal: 78,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 2,
          p2pPassed: 78,
          p2pTotal: 78,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 78,
          p2pTotal: 78,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 78,
          p2pTotal: 78,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 78,
          p2pTotal: 78,
        },
      ],
    },
    {
      instanceId: "django__django-15629",
      cells: [
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 115,
          p2pTotal: 115,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 2,
          p2pPassed: 115,
          p2pTotal: 115,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 115,
          p2pTotal: 115,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 2,
          p2pPassed: 115,
          p2pTotal: 115,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 2,
          p2pPassed: 115,
          p2pTotal: 115,
        },
      ],
    },
    {
      instanceId: "django__django-15731",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
      ],
    },
    {
      instanceId: "django__django-15814",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
      ],
    },
    {
      instanceId: "django__django-15851",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
      ],
    },
    {
      instanceId: "django__django-15863",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
      ],
    },
    {
      instanceId: "django__django-15957",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
      ],
    },
    {
      instanceId: "django__django-15987",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "grok",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
      ],
    },
    {
      instanceId: "django__django-16136",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
      ],
    },
    {
      instanceId: "django__django-16256",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
      ],
    },
    {
      instanceId: "django__django-16263",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "grok",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
      ],
    },
    {
      instanceId: "django__django-16315",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 35,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 35,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
      ],
    },
    {
      instanceId: "django__django-16429",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 2,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 4,
          p2pPassed: 17,
          p2pTotal: 21,
        },
      ],
    },
    {
      instanceId: "django__django-16560",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
      ],
    },
    {
      instanceId: "django__django-16631",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
      ],
    },
    {
      instanceId: "django__django-16642",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
      ],
    },
  ],
};
