// ⚠ 생성물 — 손으로 고치지 않는다.
// `npm run bench:swe:emit` (= scripts/bench/report.ts --emit-ours) 가 덮어쓴다.
// 정본은 실행 머신의 `results/runs.jsonl` 이고, 이 파일은 그 파생이다.
// 스키마·검증·주석은 형제 파일 `model-bench-ours.ts` 에 있다.

import type { OurBenchReport } from "./model-bench-ours";

export const OUR_BENCH_DATA: OurBenchReport = {
  meta: {
    label: "our-measured",
    dataset: "princeton-nlp/SWE-bench_Verified",
    instances: [
      "django__django-15851",
      "django__django-16429",
      "django__django-16642",
    ],
    totalRuns: 12,
    scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
    execEnv: "native-venv/macos-arm64(no-docker)",
    graderVersion: "v2(id-alias+mismatch-gate)",
    generatedAt: "2026-08-10T09:23:36.158Z",
    reportPath: "v3/docs/benchmark/generated-report.md",
    disclaimers: [
      "★이 표의 숫자는 **우리가 우리 스폰 경로로 직접 잰 값**이다. 벤더 공개치(`electron/model-bench-reference.ts`)와 **같은 표에 놓지 않는다**.",
      "★실행환경이 공식 SWE-bench Docker 이미지가 아니므로 **공식 리더보드 수치와 비교할 수 없다.** 여기서 읽어도 되는 것은 *같은 execEnv·같은 scaffold 안에서의 상대 비교*뿐이다.",
    ],
  },
  cells: [
    {
      harness: "noop",
      model: null,
      effort: null,
      graded: 3,
      resolved: 0,
      resolvedPct: 0,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      cliVersion: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "gold",
      model: null,
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      cliVersion: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-sonnet-5",
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 39,
      cliVersion: "2.1.226 (Claude Code)",
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-luna",
      effort: "medium",
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 53,
      cliVersion: "codex-cli 0.147.0",
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
  ],
  instances: [
    {
      instanceId: "django__django-15851",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
      ],
    },
    {
      instanceId: "django__django-16429",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 2,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
      ],
    },
    {
      instanceId: "django__django-16642",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
      ],
    },
  ],
};
