// ⚠ 생성물 — 손으로 고치지 않는다.
// `npm run bench:swe:emit` (= scripts/bench/report.ts --emit-ours) 가 덮어쓴다.
// 정본은 실행 머신의 `results/runs.jsonl` 이고, 이 파일은 그 파생이다.
// 스키마·검증·주석은 형제 파일 `model-bench-ours.ts` 에 있다.

import type { OurBenchReport } from "./model-bench-ours";

export const OUR_BENCH_DATA: OurBenchReport = {
  meta: {
    label: "our-measured",
    dataset: "princeton-nlp/SWE-bench_Verified",
    instances: [
      "django__django-15731",
      "django__django-15814",
      "django__django-15851",
      "django__django-15863",
      "django__django-15957",
      "django__django-15987",
      "django__django-16136",
      "django__django-16256",
      "django__django-16263",
      "django__django-16315",
      "django__django-16429",
      "django__django-16560",
      "django__django-16631",
      "django__django-16642",
    ],
    totalRuns: 165,
    scaffold:
      "marblo-swebench-spike/v1(single-shot,no-mcp,no-board) · marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
    execEnv: "native-venv/macos-arm64(no-docker)",
    graderVersion: "v2(id-alias+mismatch-gate)",
    generatedAt: "2026-08-21T03:02:03.276Z",
    reportPath: "v3/docs/benchmark/generated-report.md",
    disclaimers: [
      "★이 표의 숫자는 **우리가 우리 스폰 경로로 직접 잰 값**이다. 벤더 공개치(`electron/model-bench-reference.ts`)와 **같은 표에 놓지 않는다**.",
      "★실행환경이 공식 SWE-bench Docker 이미지가 아니므로 **공식 리더보드 수치와 비교할 수 없다.** 여기서 읽어도 되는 것은 *같은 execEnv·같은 scaffold 안에서의 상대 비교*뿐이다.",
    ],
  },
  cells: [
    {
      harness: "noop",
      model: null,
      effort: null,
      graded: 3,
      resolved: 0,
      resolvedPct: 0,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "gold",
      model: null,
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-opus-5",
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 33,
      cliVersion: "2.1.226 (Claude Code)",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-fable-5",
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 42,
      cliVersion: "2.1.226 (Claude Code)",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-sonnet-5",
      effort: null,
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 21,
      cliVersion: "2.1.226 (Claude Code)",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-sol",
      effort: "medium",
      graded: 3,
      resolved: 3,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 39,
      cliVersion: "codex-cli 0.144.5",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-luna",
      effort: "medium",
      graded: 3,
      resolved: 2,
      resolvedPct: 66.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 55,
      cliVersion: "codex-cli 0.144.5",
      vendorRoute: null,
      scaffold: "marblo-swebench-spike/v1(single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "noop",
      model: null,
      effort: null,
      graded: 12,
      resolved: 0,
      resolvedPct: 0,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "gold",
      model: null,
      effort: null,
      graded: 12,
      resolved: 12,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: null,
      cliVersion: null,
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-opus-5",
      effort: null,
      graded: 12,
      resolved: 11,
      resolvedPct: 91.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 180,
      cliVersion: "2.1.227 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-fable-5",
      effort: null,
      graded: 12,
      resolved: 12,
      resolvedPct: 100,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 94,
      cliVersion: "2.1.227 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "claude",
      model: "claude-sonnet-5",
      effort: null,
      graded: 12,
      resolved: 9,
      resolvedPct: 75,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 147,
      cliVersion: "2.1.227 (Claude Code)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-sol",
      effort: "medium",
      graded: 12,
      resolved: 11,
      resolvedPct: 91.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 92,
      cliVersion: "codex-cli 0.147.0",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-terra",
      effort: "medium",
      graded: 12,
      resolved: 9,
      resolvedPct: 75,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 61,
      cliVersion: "codex-cli 0.147.0",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.6-luna",
      effort: "medium",
      graded: 12,
      resolved: 10,
      resolvedPct: 83.33333333333334,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 94,
      cliVersion: "codex-cli 0.147.0",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "gpt-5.5",
      effort: "medium",
      graded: 12,
      resolved: 11,
      resolvedPct: 91.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 124,
      cliVersion: "codex-cli 0.147.0",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "grok",
      model: "grok-4.5",
      effort: null,
      graded: 12,
      resolved: 10,
      resolvedPct: 83.33333333333334,
      noOutput: 2,
      errored: 0,
      avgAgentSeconds: 90,
      cliVersion: "grok 1.0.0 (3cd0d0cbcebe)",
      vendorRoute: null,
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "solar-pro4",
      effort: "medium",
      graded: 12,
      resolved: 3,
      resolvedPct: 25,
      noOutput: 8,
      errored: 0,
      avgAgentSeconds: 226,
      cliVersion: "codex-cli 0.148.0",
      vendorRoute:
        "upstage/openai-compat via local responses→chat bridge (codex custom provider, apikey auth)",
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
    {
      harness: "codex",
      model: "deepseek-v4-flash",
      effort: "high",
      graded: 12,
      resolved: 11,
      resolvedPct: 91.66666666666666,
      noOutput: 0,
      errored: 0,
      avgAgentSeconds: 73,
      cliVersion: "codex-cli 0.149.0",
      vendorRoute:
        "deepseek/responses-native direct (codex custom provider, apikey auth, model_catalog_json → apply_patch=freeform)",
      scaffold:
        "marblo-swebench-spike/v2(12-mixed-difficulty,single-shot,no-mcp,no-board)",
      execEnv: "native-venv/macos-arm64(no-docker)",
      graderVersion: "v2(id-alias+mismatch-gate)",
    },
  ],
  instances: [
    {
      instanceId: "django__django-15731",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 58,
          p2pTotal: 58,
        },
      ],
    },
    {
      instanceId: "django__django-15814",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 29,
          p2pTotal: 29,
        },
      ],
    },
    {
      instanceId: "django__django-15851",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 8,
          p2pTotal: 8,
        },
      ],
    },
    {
      instanceId: "django__django-15863",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 9,
          p2pTotal: 9,
        },
      ],
    },
    {
      instanceId: "django__django-15957",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 89,
          p2pTotal: 89,
        },
      ],
    },
    {
      instanceId: "django__django-15987",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "grok",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 52,
          p2pTotal: 52,
        },
      ],
    },
    {
      instanceId: "django__django-16136",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 2,
          f2pTotal: 2,
          p2pPassed: 7,
          p2pTotal: 7,
        },
      ],
    },
    {
      instanceId: "django__django-16256",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 9,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 6,
          f2pTotal: 9,
          p2pPassed: 53,
          p2pTotal: 53,
        },
      ],
    },
    {
      instanceId: "django__django-16263",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "grok",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 3,
          f2pTotal: 3,
          p2pPassed: 100,
          p2pTotal: 100,
        },
      ],
    },
    {
      instanceId: "django__django-16315",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 35,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 35,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 42,
          p2pTotal: 42,
        },
      ],
    },
    {
      instanceId: "django__django-16429",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 2,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 4,
          f2pTotal: 4,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 1,
          f2pTotal: 4,
          p2pPassed: 17,
          p2pTotal: 21,
        },
      ],
    },
    {
      instanceId: "django__django-16560",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 8,
          f2pTotal: 8,
          p2pPassed: 66,
          p2pTotal: 66,
        },
      ],
    },
    {
      instanceId: "django__django-16631",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "claude",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "grok",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 12,
          p2pTotal: 12,
        },
      ],
    },
    {
      instanceId: "django__django-16642",
      cells: [
        {
          harness: "noop",
          resolved: false,
          f2pPassed: 0,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "gold",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "claude",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
        {
          harness: "codex",
          resolved: true,
          f2pPassed: 1,
          f2pTotal: 1,
          p2pPassed: 21,
          p2pTotal: 21,
        },
      ],
    },
  ],
};
